import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header";
import { afcand } from "./_constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={afcand.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
